dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements/dev.txt
script:
  - inv install --dev
  - inv build -o build
  - inv test -m build