name: Release

on:
  push:
    tags:
      - v*

jobs:
  debug:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  test:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        include:  # match Python bitness shipped with Galaxy
          - os: macOS-latest
            arch: x64
          - os: windows-latest
            arch: x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: ${{ matrix.arch }}
      - name: Install
        run: python -m pip install -r requirements-dev.txt
      - name: Run Tests
        run: |
          inv release --for-tag ${{ github.ref }}