name: Release

on:
  push:
    tags:
      - 'v*'
      - '!v*-*'  # pre-releases

jobs:
  release:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        include:  # match Python bitness shipped with Galaxy
          - os: macOS-latest
            arch: x64
          - os: windows-latest
            arch: x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: ${{ matrix.arch }}
      - name: Install requirements
        run: python -m pip install -r requirements-dev.txt
      - name: Test, Pack and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: inv release --automa
      - name: VirusTotal GitHub Action
        uses: crazy-max/ghaction-virustotal@v3.0.0
        with: ...
